# Generated by Django 6.0.1 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_desc_webpage_s_name_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='webpage',
            name='sort',
            field=models.IntegerField(null=True),
        ),
    ]
