# Generated by Django 6.0.1 on 2026-01-13 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_topic_created_at_webpage_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='Webpages',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='desc',
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.webpage'),
        ),
    ]
